services:
  - type: web
    name: angular-ui
    env: node
    buildCommand: npm install && cd AngularUI && npm install && npm run build
    startCommand: cd AngularUI && node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: PORT
        value: 10000
      - key: API_URL
        value: https://api-prova-tecnica-csharp.onrender.com
  - type: web
    name: api
    env: docker
    dockerfilePath: ./Api/Dockerfile
    dockerContext: ./Api
    envVars:
      - key: DATABASE_URL
        value: "Server=sql.render.com;Database=prova_tecnica_db;User Id=admin;Password=password123!;TrustServerCertificate=True;MultipleActiveResultSets=true;Connection Timeout=60"
      - key: ASPNETCORE_ENVIRONMENT
        value: Production